sonar.projectKey=Prabhakar-cg_devsuite
sonar.organization=prabha

# Exclude third-party vendored libraries and test files from analysis
sonar.exclusions=static/libs/**,static/*.js,static/vendor/**,tests/**
sonar.security.exclusions=tests/**,static/libs/**
